### ISSUE TITLE
HeightMapShape3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#103]
## Description

This issue tracks the progress of implementing the functionality of Godot's `HeightMapShape3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- ~~Partial (functional)~~
- **Done (as much as it can be)** 👈
- ~~Done (completely)~~

## Links

Documentation: [`HeightMapShape3D`](https://docs.godotengine.org/en/latest/classes/class_heightmapshape3d.html)
Inherits: [`Shape3D`](https://docs.godotengine.org/en/latest/classes/class_shape3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Uncategorized

- [x] Map Width (`map_width`)
- [x] Map Depth (`map_depth`)
- [x] Map Data (`map_data`)

### Uncategorized

- [ ] 🛑 Custom Solver Bias (`custom_solver_bias`)
    - Not supported by Jolt
- [x] Margin (`margin`)

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has had new issues created for it.
