### ISSUE TITLE
HingeJoint3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#107]
## Description

This issue tracks the progress of implementing the functionality of Godot's `HingeJoint3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- ~~Partial (functional)~~
- **Done (as much as it can be)** 👈
- ~~Done (completely)~~

## Links

Documentation: [`HingeJoint3D`](https://docs.godotengine.org/en/latest/classes/class_hingejoint3d.html)
Inherits: [`Joint3D`](https://docs.godotengine.org/en/latest/classes/class_joint3d.html), [`Node3D`](https://docs.godotengine.org/en/latest/classes/class_node3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Params

- [ ] 🛑 Bias (`PARAM_BIAS`)
    - Not compatible with Jolt's `HingeConstraint`

### Angular Limit

- [x] Enable (`FLAG_USE_LIMIT`)
- [x] Upper (`PARAM_LIMIT_UPPER`)
- [x] Lower (`PARAM_LIMIT_LOWER`)
- [ ] 🛑 Bias (`PARAM_LIMIT_BIAS`)
    - Not compatible with Jolt's `HingeConstraint`
- [ ] 🛑 Softness (`PARAM_LIMIT_SOFTNESS`)
    - Not compatible with Jolt's `HingeConstraint`
- [ ] 🛑 Relaxation (`PARAM_LIMIT_RELAXATION`)
    - Not compatible with Jolt's `HingeConstraint`

### Motor

- [x] Enable (`FLAG_ENABLE_MOTOR`)
- [x] Target Velocity (`PARAM_MOTOR_TARGET_VELOCITY`)
- [x] Max Impulse (`PARAM_MOTOR_MAX_IMPULSE`)

### Uncategorized

- [x] Node A (`node_a`)
- [x] Node B (`node_b`)
- [ ] 🛑 Solver Priority (`solver_priority`)
    - Not supported by Jolt
- [x] Exclude Nodes From Collision (`exclude_nodes_from_collision`)

### Transform

- [x] Position (`position`)
- [x] Rotation (`rotation`)
- [x] Scale (`scale`)

## Methods

- [x] `get_flag`
- [x] `get_param`
- [x] `set_flag`
- [x] `set_param`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has had new issues created for it.
