### ISSUE TITLE
ConeTwistJoint3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#108]
## Description

This issue tracks the progress of implementing the functionality of Godot's `ConeTwistJoint3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- ~~Partial (functional)~~
- **Done (as much as it can be)** 👈
- ~~Done (completely)~~

## Links

Documentation: [`ConeTwistJoint3D`](https://docs.godotengine.org/en/latest/classes/class_conetwistjoint3d.html)
Inherits: [`Joint3D`](https://docs.godotengine.org/en/latest/classes/class_joint3d.html), [`Node3D`](https://docs.godotengine.org/en/latest/classes/class_node3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Uncategorized

- [x] Swing Span (`swing_span`)
- [x] Twist Span (`twist_span`)
- [ ] 🛑 Bias (`bias`)
    - Not compatible with Jolt's `SwingTwistConstraint`
- [ ] 🛑 Softness (`softness`)
    - Not compatible with Jolt's `SwingTwistConstraint`
- [ ] 🛑 Relaxation (`relaxation`)
    - Not compatible with Jolt's `SwingTwistConstraint`

### Uncategorized

- [x] Node A (`node_a`)
- [x] Node B (`node_b`)
- [ ] 🛑 Solver Priority (`solver_priority`)
    - Not supported by Jolt
- [x] Exclude Nodes From Collision (`exclude_nodes_from_collision`)

### Transform

- [x] Position (`position`)
- [x] Rotation (`rotation`)
- [x] Scale (`scale`)
