### ISSUE TITLE
SliderJoint3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#109]
## Description

This issue tracks the progress of implementing the functionality of Godot's `SliderJoint3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- ~~Partial (functional)~~
- **Done (as much as it can be)** 👈
- ~~Done (completely)~~

## Links

Documentation: [`SliderJoint3D`](https://docs.godotengine.org/en/latest/classes/class_sliderjoint3d.html)
Inherits: [`Joint3D`](https://docs.godotengine.org/en/latest/classes/class_joint3d.html), [`Node3D`](https://docs.godotengine.org/en/latest/classes/class_node3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Linear Limit

- [x] Upper Distance (`PARAM_LINEAR_LIMIT_UPPER`)
- [x] Lower Distance (`PARAM_LINEAR_LIMIT_LOWER`)
- [ ] 🛑 Softness (`PARAM_LINEAR_LIMIT_SOFTNESS`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Restitution (`PARAM_LINEAR_LIMIT_RESTITUTION`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Damping (`PARAM_LINEAR_LIMIT_DAMPING`)
    - Not compatible with Jolt's `SliderConstraint`

### Linear Motion

- [ ] 🛑 Softness (`PARAM_LINEAR_MOTION_SOFTNESS`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Restitution (`PARAM_LINEAR_MOTION_RESTITUTION`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Damping (`PARAM_LINEAR_MOTION_DAMPING`)
    - Not compatible with Jolt's `SliderConstraint`

### Linear Ortho

- [ ] 🛑 Softness (`PARAM_LINEAR_ORTHOGONAL_SOFTNESS`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Restitution (`PARAM_LINEAR_ORTHOGONAL_RESTITUTION`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Damping (`PARAM_LINEAR_ORTHOGONAL_DAMPING`)
    - Not compatible with Jolt's `SliderConstraint`

### Angular Limit

- [ ] 🛑 Upper Angle (`PARAM_ANGULAR_LIMIT_UPPER`)
    - Not compatible with Jolt's `SliderConstraint`. Use `Generic6DOFJoint3D` instead.
- [ ] 🛑 Lower Angle (`PARAM_ANGULAR_LIMIT_LOWER`)
    - Not compatible with Jolt's `SliderConstraint`. Use `Generic6DOFJoint3D` instead.
- [ ] 🛑 Softness (`PARAM_ANGULAR_LIMIT_SOFTNESS`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Restitution (`PARAM_ANGULAR_LIMIT_RESTITUTION`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Damping (`PARAM_ANGULAR_LIMIT_DAMPING`)
    - Not compatible with Jolt's `SliderConstraint`

### Angular Motion

- [ ] 🛑 Softness (`PARAM_ANGULAR_MOTION_SOFTNESS`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Restitution (`PARAM_ANGULAR_MOTION_RESTITUTION`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Damping (`PARAM_ANGULAR_MOTION_DAMPING`)
    - Not compatible with Jolt's `SliderConstraint`

### Angular Ortho

- [ ] 🛑 Softness (`PARAM_ANGULAR_ORTHOGONAL_SOFTNESS`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Restitution (`PARAM_ANGULAR_ORTHOGONAL_RESTITUTION`)
    - Not compatible with Jolt's `SliderConstraint`
- [ ] 🛑 Damping (`PARAM_ANGULAR_ORTHOGONAL_DAMPING`)
    - Not compatible with Jolt's `SliderConstraint`

### Uncategorized

- [x] Node A (`node_a`)
- [x] Node B (`node_b`)
- [ ] 🛑 Solver Priority (`solver_priority`)
    - Not supported by Jolt
- [x] Exclude Nodes From Collision (`exclude_nodes_from_collision`)

### Transform

- [x] Position (`position`)
- [x] Rotation (`rotation`)
- [x] Scale (`scale`)

## Methods

- [x] `get_param`
- [x] `set_param`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has had new issues created for it.
