### ISSUE TITLE
Generic6DOFJoint3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#110]
## Description

This issue tracks the progress of implementing the functionality of Godot's `Generic6DOFJoint3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- ~~Partial (functional)~~
- **Done (as much as it can be)** 👈
- ~~Done (completely)~~

## Links

Documentation: [`Generic6DOFJoint3D`](https://docs.godotengine.org/en/latest/classes/class_generic6dofjoint3d.html)
Inherits: [`Joint3D`](https://docs.godotengine.org/en/latest/classes/class_joint3d.html), [`Node3D`](https://docs.godotengine.org/en/latest/classes/class_node3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

###  Linear Limit

- [x] Enabled (`FLAG_ENABLE_LINEAR_LIMIT`)
- [x] Upper Distance (`PARAM_LINEAR_UPPER_LIMIT`)
- [x] Lower Distance (`PARAM_LINEAR_LOWER_LIMIT`)
- [ ] 🛑 Softness (`PARAM_LINEAR_LIMIT_SOFTNESS`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Restitution (`PARAM_LINEAR_RESTITUTION`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Damping (`PARAM_LINEAR_DAMPING`)
    - Not compatible with Jolt's `SixDOFConstraint`

### Linear Motor

- [x] Enabled (`FLAG_ENABLE_LINEAR_MOTOR`)
- [x] Target Velocity (`PARAM_LINEAR_MOTOR_TARGET_VELOCITY`)
- [x] Force Limit (`PARAM_LINEAR_MOTOR_FORCE_LIMIT`)

### Linear Spring

- [ ] 🛑 Enabled (`FLAG_ENABLE_LINEAR_SPRING`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Stiffness (`PARAM_LINEAR_SPRING_STIFFNESS`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Damping (`PARAM_LINEAR_SPRING_DAMPING`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Equilibrium Point (`PARAM_LINEAR_SPRING_EQUILIBRIUM_POINT`)
    - Not compatible with Jolt's `SixDOFConstraint`

### Angular Limit

- [x] Enabled (`FLAG_ENABLE_ANGULAR_LIMIT`)
- [x] Upper Angle (`PARAM_ANGULAR_UPPER_LIMIT`)
- [x] Lower Angle (`PARAM_ANGULAR_LOWER_LIMIT`)
- [ ] 🛑 Softness (`PARAM_ANGULAR_LIMIT_SOFTNESS`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Restitution (`PARAM_ANGULAR_RESTITUTION`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Damping (`PARAM_ANGULAR_DAMPING`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Force Limit (`PARAM_ANGULAR_FORCE_LIMIT`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 ERP (`PARAM_ANGULAR_ERP`)
    - Not compatible with Jolt's `SixDOFConstraint`

### Angular Motor

- [x] Enabled (`FLAG_ENABLE_MOTOR`)
- [x] Target Velocity (`PARAM_ANGULAR_MOTOR_TARGET_VELOCITY`)
- [x] Force Limit (`PARAM_ANGULAR_MOTOR_FORCE_LIMIT`)

### Angular Spring

- [ ] 🛑 Enabled (`FLAG_ENABLE_ANGULAR_SPRING`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Stiffness (`PARAM_ANGULAR_SPRING_STIFFNESS`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Damping (`PARAM_ANGULAR_SPRING_DAMPING`)
    - Not compatible with Jolt's `SixDOFConstraint`
- [ ] 🛑 Equilibrium Point (`PARAM_ANGULAR_SPRING_EQUILIBRIUM_POINT`)
    - Not compatible with Jolt's `SixDOFConstraint`

### Uncategorized

- [x] Node A (`node_a`)
- [x] Node B (`node_b`)
- [ ] 🛑 Solver Priority (`solver_priority`)
    - Not supported by Jolt
- [x] Exclude Nodes From Collision (`exclude_nodes_from_collision`)

### Transform

- [x] Position (`position`)
- [x] Rotation (`rotation`)
- [x] Scale (`scale`)

### Methods

- [x] `get_flag_x`
- [x] `get_flag_y`
- [x] `get_flag_z`
- [x] `get_param_x`
- [x] `get_param_y`
- [x] `get_param_z`
- [x] `set_flag_x`
- [x] `set_flag_y`
- [x] `set_flag_z`
- [x] `set_param_x`
- [x] `set_param_y`
- [x] `set_param_z`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has had new issues created for it.
