### ISSUE TITLE
PhysicsDirectBodyState3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#111]
## Description

This issue tracks the progress of implementing the functionality of Godot's `PhysicsDirectBodyState3D` object. Below you'll find all user-facing properties and methods, including ones inherited from relevant classes. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- ~~Partial (functional)~~
- **Done (as much as it can be)** 👈
- ~~Done (completely)~~

## Links

Documentation: [`PhysicsDirectBodyState3D`](https://docs.godotengine.org/en/latest/classes/class_physicsdirectbodystate3d.html)
Inherits: N/A

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Uncategorized

- [x] `angular_velocity`
- [x] `center_of_mass` (read-only)
- [x] `center_of_mass_local` (read-only)
- [x] `inverse_inertia` (read-only)
- [x] `inverse_inertia_tensor` (read-only)
- [x] `inverse_mass` (read-only)
- [x] `linear_velocity`
- [x] `principal_inertia_axes` (read-only)
- [x] `sleeping`
- [x] `step` (read-only)
- [x] `total_angular_damp` (read-only)
- [x] `total_gravity` (read-only)
- [x] `total_linear_damp` (read-only)
- [x] `transform`

## Methods

- [x] `add_constant_central_force`
- [x] `add_constant_force`
- [x] `add_constant_torque`
- [x] `apply_central_force`
- [x] `apply_central_impulse`
- [x] `apply_force`
- [x] `apply_impulse`
- [x] `apply_torque`
- [x] `apply_torque_impulse`
- [x] `get_constant_force`
- [x] `get_constant_torque`
- [x] `get_contact_collider`
- [x] `get_contact_collider_id`
- [x] `get_contact_collider_object`
- [x] `get_contact_collider_position`
- [x] `get_contact_collider_shape`
- [x] `get_contact_collider_velocity_at_position`
- [x] `get_contact_count`
- [x] `get_contact_impulse`
- [x] `get_contact_local_normal`
- [x] `get_contact_local_position`
- [x] `get_contact_local_shape`
- [x] `get_space_state`
- [x] `get_velocity_at_local_position`
- [ ] 🛑 `integrate_forces`
    - Not supported by Jolt
- [x] `set_constant_force`
- [x] `set_constant_torque`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has had new issues created for it.
