### ISSUE TITLE
PhysicsServer3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#113]
## Description

This issue tracks the progress of implementing the functionality of Godot's `PhysicsServer3D` object. Below you'll find all user-facing properties and methods, including ones inherited from relevant classes. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- ~~Partial (functional)~~
- **Done (as much as it can be)** 👈
- ~~Done (completely)~~

## Links

Documentation: [`PhysicsServer3D`](https://docs.godotengine.org/en/latest/classes/class_physicsserver3d.html)
Inherits: N/A

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

## Methods

- [x] `area_add_shape`
- [x] `area_attach_object_instance_id`
- [x] `area_clear_shapes`
- [x] `area_create`
- [x] `area_get_collision_layer`
- [x] `area_get_collision_mask`
- [x] `area_get_object_instance_id`
- [x] `area_get_param`
- [x] `area_get_shape`
- [x] `area_get_shape_count`
- [x] `area_get_shape_transform`
- [x] `area_get_space`
- [x] `area_get_transform`
- [x] `area_remove_shape`
- [x] `area_set_area_monitor_callback`
- [x] `area_set_collision_layer`
- [x] `area_set_collision_mask`
- [x] `area_set_monitor_callback`
- [x] `area_set_monitorable`
- [x] `area_set_param`
- [x] `area_set_ray_pickable`
- [x] `area_set_shape`
- [x] `area_set_shape_disabled`
- [x] `area_set_shape_transform`
- [x] `area_set_space`
- [x] `area_set_transform`
- [x] `body_add_collision_exception`
- [x] `body_add_constant_central_force`
- [x] `body_add_constant_force`
- [x] `body_add_constant_torque`
- [x] `body_add_shape`
- [x] `body_apply_central_force`
- [x] `body_apply_central_impulse`
- [x] `body_apply_force`
- [x] `body_apply_impulse`
- [x] `body_apply_torque`
- [x] `body_apply_torque_impulse`
- [x] `body_attach_object_instance_id`
- [x] `body_clear_shapes`
- [x] `body_create`
- [x] `body_get_collision_layer`
- [x] `body_get_collision_mask`
- [x] `body_get_collision_priority`
- [x] `body_get_constant_force`
- [x] `body_get_constant_torque`
- [x] `body_get_direct_state`
- [x] `body_get_max_contacts_reported`
- [x] `body_get_mode`
- [x] `body_get_object_instance_id`
- [x] `body_get_param`
- [x] `body_get_shape`
- [x] `body_get_shape_count`
- [x] `body_get_shape_transform`
- [x] `body_get_space`
- [x] `body_get_state`
- [x] `body_is_axis_locked`
- [x] `body_is_continuous_collision_detection_enabled`
- [x] `body_is_omitting_force_integration`
- [x] `body_remove_collision_exception`
- [x] `body_remove_shape`
- [x] `body_reset_mass_properties`
- [x] `body_set_axis_lock`
- [x] `body_set_axis_velocity`
- [x] `body_set_collision_layer`
- [x] `body_set_collision_mask`
- [x] `body_set_collision_priority`
- [x] `body_set_constant_force`
- [x] `body_set_constant_torque`
- [x] `body_set_enable_continuous_collision_detection`
- [x] `body_set_force_integration_callback`
- [x] `body_set_max_contacts_reported`
- [x] `body_set_mode`
- [ ] 🛑 `body_set_omit_force_integration`
- [x] `body_set_param`
- [x] `body_set_ray_pickable`
- [x] `body_set_shape`
- [x] `body_set_shape_disabled`
- [x] `body_set_shape_transform`
- [x] `body_set_space`
- [x] `body_set_state`
- [x] `body_test_motion`
- [x] `box_shape_create`
- [x] `capsule_shape_create`
- [x] `concave_polygon_shape_create`
- [x] `cone_twist_joint_get_param`
- [x] `cone_twist_joint_set_param`
- [x] `convex_polygon_shape_create`
- [ ] 🛑 `custom_shape_create`
- [x] `cylinder_shape_create`
- [x] `free_rid`
- [x] `generic_6dof_joint_get_flag`
- [x] `generic_6dof_joint_get_param`
- [x] `generic_6dof_joint_set_flag`
- [x] `generic_6dof_joint_set_param`
- [ ] 🛑 `get_process_info`
- [x] `heightmap_shape_create`
- [x] `hinge_joint_get_flag`
- [x] `hinge_joint_get_param`
- [x] `hinge_joint_set_flag`
- [x] `hinge_joint_set_param`
- [x] `joint_clear`
- [x] `joint_create`
- [ ] 🛑 `joint_get_solver_priority`
- [x] `joint_get_type`
- [x] `joint_make_cone_twist`
- [x] `joint_make_generic_6dof`
- [x] `joint_make_hinge`
- [x] `joint_make_pin`
- [x] `joint_make_slider`
- [ ] 🛑 `joint_set_solver_priority`
- [x] `pin_joint_get_local_a`
- [x] `pin_joint_get_local_b`
- [x] `pin_joint_get_param`
- [x] `pin_joint_set_local_a`
- [x] `pin_joint_set_local_b`
- [x] `pin_joint_set_param`
- [x] `separation_ray_shape_create`
- [x] `set_active`
- [x] `shape_get_data`
- [x] `shape_get_type`
- [x] `shape_set_data`
- [x] `slider_joint_get_param`
- [x] `slider_joint_set_param`
- [ ] 🛑 `soft_body_get_bounds`
- [x] `space_create`
- [x] `space_get_direct_state`
- [x] `space_get_param`
- [x] `space_is_active`
- [x] `space_set_active`
- [x] `space_set_param`
- [x] `sphere_shape_create`
- [ ] 🛑 `world_boundary_shape_create`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has had new issues created for it.
