### ISSUE TITLE
StaticBody3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#92]
## Description

This issue tracks the progress of implementing the functionality of Godot's `StaticBody3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- **Partial (functional)** 👈
- Done (as much as it can be)
- ~~Done (completely)~~

## Links

Documentation: [`StaticBody3D`](https://docs.godotengine.org/en/latest/classes/class_staticbody3d.html)
Inherits: [`PhysicsBody3D`](https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html), [`CollisionObject3D`](https://docs.godotengine.org/en/latest/classes/class_collisionobject3d.html), [`Node3D`](https://docs.godotengine.org/en/latest/classes/class_node3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Uncategorized

- [x] Physics Material Override (`physics_material_override`)
    - [x] Friction (`friction`)
    - [x] Rough (`rough`)
    - [x] Bounce (`bounce`)
    - [x] Absorbent (`absorbent`)
- [ ] 🛑 Constant Linear Velocity (`constant_linear_velocity`)
    - Not supported by Jolt
- [ ] 🛑 Constant Angular Velocity (`constant_angular_velocity`)
    - Not supported by Jolt

### Axis Lock

- [x] Linear X (`BODY_AXIS_LINEAR_X`)
- [x] Linear Y (`BODY_AXIS_LINEAR_Y`)
- [x] Linear Z (`BODY_AXIS_LINEAR_Z`)
- [x] Angular X (`BODY_AXIS_ANGULAR_X`)
- [x] Angular Y (`BODY_AXIS_ANGULAR_Y`)
- [x] Angular Z (`BODY_AXIS_ANGULAR_Z`)

### Uncategorized

- [x] Disable Mode (`disable_mode`)
    - [x] Remove (`DISABLE_MODE_REMOVE`)
    - [x] Static (`DISABLE_MODE_MAKE_STATIC`)
    - [x] Active (`DISABLE_MODE_KEEP_ACTIVE`)

### Collision

- [x] Layer (`collision_layer`)
- [x] Mask (`collision_mask`)
- [x] Priority (`collision_priority`)

### Input

- [ ] 🚧 Ray Pickable (`input_ray_pickable`)
    - Technically implemented, but hardcoded to `true` until Godot 4.1
- [x] Capture on Drag (`input_capture_on_drag`)

### Transform

- [x] Position (`position`)
- [x] Rotation (`rotation`)
- [x] Scale (`scale`)

## Methods (PhysicsBody3D)

- [x] `add_collision_exception_with`
- [x] `remove_collision_exception_with`
- [x] `get_axis_lock`
- [x] `get_collision_exception`
- [ ] 🚧 `move_and_collide`
    - Works, but `recovery_as_collision` is hardcoded to `true` until Godot 4.1
- [x] `set_axis_lock`
- [ ] 🚧 `test_move`
    - Works, but `recovery_as_collision` is hardcoded to `true` until Godot 4.1

## Methods (CollisionObject3D)

- [x] `_input_event`
- [x] `_mouse_enter`
- [x] `_mouse_exit`
- [x] `create_shape_owner`
- [x] `get_collision_layer_value`
- [x] `get_collision_mask_value`
- [x] `get_rid`
- [x] `get_shape_owners`
- [x] `is_shape_owner_disabled`
- [x] `remove_shape_owner`
- [x] `set_collision_layer_value`
- [x] `set_collision_mask_value`
- [x] `shape_find_owner`
- [x] `shape_owner_add_shape`
- [x] `shape_owner_clear_shapes`
- [x] `shape_owner_get_owner`
- [x] `shape_owner_get_shape`
- [x] `shape_owner_get_shape_count`
- [x] `shape_owner_get_shape_index`
- [x] `shape_owner_get_transform`
- [x] `shape_owner_remove_shape`
- [x] `shape_owner_set_disabled`
- [x] `shape_owner_set_transform`

## Signals (CollisionObject3D)

- [x] `input_event`
- [x] `mouse_entered`
- [x] `mouse_exited`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed and locked.

Any remaining work has been promoted to a separate issue.

🫡
