### ISSUE TITLE
RigidBody3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#93]
## Description

This issue tracks the progress of implementing the functionality of Godot's `RigidBody3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- **Partial (functional)** 👈
- Done (as much as it can be)
- ~~Done (completely)~~

## Links

Documentation: [`RigidBody3D`](https://docs.godotengine.org/en/latest/classes/class_rigidbody3d.html)
Inherits: [`PhysicsBody3D`](https://docs.godotengine.org/en/latest/classes/class_physicsbody3d.html), [`CollisionObject3D`](https://docs.godotengine.org/en/latest/classes/class_collisionobject3d.html), [`Node3D`](https://docs.godotengine.org/en/latest/classes/class_node3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Uncategorized

- [x] Mass (`mass`)
- [x] Inertia (`inertia`)
- [x] Center of Mass Mode (`center_of_mass_mode`)
    - [x] Auto (`CENTER_OF_MASS_MODE_AUTO`)
    - [x] Custom (`CENTER_OF_MASS_MODE_CUSTOM`)
- [x] Physical Material Override (`physics_material_override`)
    - [x] Friction (`friction`)
    - [x] Rough (`rough`)
    - [x] Bounce (`bounce`)
    - [x] Absorbent (`absorbent`)
- [x] Gravity Scale (`gravity_scale`)
- [ ] 🛑 Custom Integrator (`custom_integrator`)
    - Not supported by Jolt
- [x] Continuous CD (`continuous_cd`)
- [x] Max Contacts Reported (`max_contacts_reported`)
- [x] Contact Monitor (`contact_monitor`)
- [x] Sleeping (`sleeping`)
- [x] Can Sleep (`can_sleep`)
- [x] Lock Rotation (`lock_rotation`)
- [x] Freeze (`freeze`)
- [x] Freeze Mode (`freeze_mode`)
    - [x] Static (`FREEZE_MODE_STATIC`)
    - [x] Kinematic (`FREEZE_MODE_KINEMATIC`)

### Linear

- [x] Velocity (`linear_velocity`)
- [x] Damp Mode (`linear_damp_mode`)
    - [x] Combine (`DAMP_MODE_COMBINE`)
    - [x] Replace (`DAMP_MODE_REPLACE`)
- [x] Damp (`linear_damp`)

### Angular

- [x] Velocity (`angular_velocity`)
- [x] Damp Mode (`angular_damp_mode`)
    - [x] Combine (`DAMP_MODE_COMBINE`)
    - [x] Replace (`DAMP_MODE_REPLACE`)
- [x] Damp (`angular_damp`)

### Constant Forces

- [x] Force (`constant_force`)
- [x] Torque (`constant_torque`)

### Axis Lock

- [x] Linear X (`BODY_AXIS_LINEAR_X`)
- [x] Linear Y (`BODY_AXIS_LINEAR_Y`)
- [x] Linear Z (`BODY_AXIS_LINEAR_Z`)
- [x] Angular X (`BODY_AXIS_ANGULAR_X`)
- [x] Angular Y (`BODY_AXIS_ANGULAR_Y`)
- [x] Angular Z (`BODY_AXIS_ANGULAR_Z`)

### Uncategorized

- [x] Disable Mode (`disable_mode`)
    - [x] Remove (`DISABLE_MODE_REMOVE`)
    - [x] Static (`DISABLE_MODE_MAKE_STATIC`)
    - [x] Active (`DISABLE_MODE_KEEP_ACTIVE`)

### Collision

- [x] Layer (`collision_layer`)
- [x] Mask (`collision_mask`)
- [x] Priority (`collision_priority`)

### Input

- [ ] 🚧 Ray Pickable (`input_ray_pickable`)
    - Technically implemented, but hardcoded to `true` until Godot 4.1
- [x] Capture on Drag (`input_capture_on_drag`)

### Transform

- [x] Position (`position`)
- [x] Rotation (`rotation`)
- [x] Scale (`scale`)

## Methods

- [x] `_integrate_forces`
- [x] `add_constant_central_force`
- [x] `add_constant_force`
- [x] `add_constant_torque`
- [x] `apply_central_force`
- [x] `apply_central_torque`
- [x] `apply_central_impulse`
- [x] `apply_force`
- [x] `apply_impulse`
- [x] `apply_torque`
- [x] `apply_torque_impulse`
- [x] `get_colliding_bodies`
- [x] `get_contact_count`
- [x] `get_inverse_inertia_tensor`
- [x] `set_axis_velocity`

## Methods (PhysicsBody3D)

- [x] `add_collision_exception_with`
- [x] `remove_collision_exception_with`
- [x] `get_axis_lock`
- [x] `get_collision_exception`
- [ ] 🚧 `move_and_collide`
    - Works, but `recovery_as_collision` is hardcoded to `true` until Godot 4.1
- [x] `set_axis_lock`
- [ ] 🚧 `test_move`
    - Works, but `recovery_as_collision` is hardcoded to `true` until Godot 4.1

## Methods (CollisionObject3D)

- [x] `_input_event`
- [x] `_mouse_enter`
- [x] `_mouse_exit`
- [x] `create_shape_owner`
- [x] `get_collision_layer_value`
- [x] `get_collision_mask_value`
- [x] `get_rid`
- [x] `get_shape_owners`
- [x] `is_shape_owner_disabled`
- [x] `remove_shape_owner`
- [x] `set_collision_layer_value`
- [x] `set_collision_mask_value`
- [x] `shape_find_owner`
- [x] `shape_owner_add_shape`
- [x] `shape_owner_clear_shapes`
- [x] `shape_owner_get_owner`
- [x] `shape_owner_get_shape`
- [x] `shape_owner_get_shape_count`
- [x] `shape_owner_get_shape_index`
- [x] `shape_owner_get_transform`
- [x] `shape_owner_remove_shape`
- [x] `shape_owner_set_disabled`
- [x] `shape_owner_set_transform`

## Signals

- [x] `body_entered`
- [x] `body_exited`
- [x] `body_shape_entered`
- [x] `body_shape_exited`
- [x] `sleeping_state_changed`

## Signals (CollisionObject3D)

- [x] `input_event`
- [x] `mouse_entered`
- [x] `mouse_exited`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has been promoted to new issues.
