### ISSUE TITLE
Area3D

### ISSUE THREAD

**Issue by mihe** [godot-jolt/godot-jolt#95]
## Description

This issue tracks the progress of implementing the functionality of Godot's `Area3D` node type. Below you'll find all user-facing properties, methods and signals, including ones inherited from relevant node types. If you notice any missing from this list, please leave a comment down below.

## Status

- ~~Not supported~~
- ~~Not started~~
- ~~Partial (not functional)~~
- **Partial (functional)** 👈
- Done (as much as it can be)
- ~~Done (completely)~~

## Links

Documentation: [`Area3D`](https://docs.godotengine.org/en/latest/classes/class_area3d.html)
Inherits: [`CollisionObject3D`](https://docs.godotengine.org/en/latest/classes/class_collisionobject3d.html), [`Node3D`](https://docs.godotengine.org/en/latest/classes/class_node3d.html)

## Legend

- 🚧 indicates a partial, incomplete or broken implementation.
- 🛑 indicates that it's blocked or incompatible with Jolt in some way.

### Uncategorized

- [x] Monitoring (`monitoring`)
- [x] Monitorable (`monitorable`)
- [x] Priority (`priority`)

### Gravity

- [x] Space Override (`gravity_space_override`)
    - [x] Combine (`SPACE_OVERRIDE_COMBINE`)
    - [x] Combine-Replace (`SPACE_OVERRIDE_COMBINE_REPLACE`)
    - [x] Replace (`SPACE_OVERRIDE_REPLACE`)
    - [x] Replace-Combine (`SPACE_OVERRIDE_REPLACE_COMBINE`)
- [x] Point (`gravity_point`)
- [x] Point Unit Distance (`gravity_point_unit_distance`)
- [x] Point Center (`gravity_point_center`)
- [x] Direction (`gravity_direction`)
- [x] Gravity (`gravity`)

### Linear Damp

- [x] Space Override (`linear_damp_space_override`)
    - [x] Combine (`SPACE_OVERRIDE_COMBINE`)
    - [x] Combine-Replace (`SPACE_OVERRIDE_COMBINE_REPLACE`)
    - [x] Replace (`SPACE_OVERRIDE_REPLACE`)
    - [x] Replace-Combine (`SPACE_OVERRIDE_REPLACE_COMBINE`)
- [x] Linear Damp (`linear_damp`)

### Angular Damp

- [x] Space Override (`angular_damp_space_override`)
    - [x] Combine (`SPACE_OVERRIDE_COMBINE`)
    - [x] Combine-Replace (`SPACE_OVERRIDE_COMBINE_REPLACE`)
    - [x] Replace (`SPACE_OVERRIDE_REPLACE`)
    - [x] Replace-Combine (`SPACE_OVERRIDE_REPLACE_COMBINE`)
- [x] Angular Damp (`angular_damp`)

### Wind

- [ ] 🛑 Force Magnitude (`wind_force_magnitude`)
    - Only relevant for `SoftBody3D`, which isn't supported
- [ ] 🛑 Attenuation Factor (`wind_attenuation_factor`)
    - Only relevant for `SoftBody3D`, which isn't supported
- [ ] 🛑 Source Path (`wind_source_path`)
    - Only relevant for `SoftBody3D`, which isn't supported

### Audio Bus

- [x] Override (`audio_bus_override`)
- [x] Name (`audio_bus_name`)

### Reverb Bus

- [x] Enabled (`reverb_bus_enabled`)
- [x] Name (`reverb_bus_name`)
- [x] Amount (`reverb_bus_amount`)
- [x] Uniformity (`reverb_bus_uniformity`)

### Uncategorized

- [x] Disable Mode (`disable_mode`)
    - [x] Remove (`DISABLE_MODE_REMOVE`)
    - [x] Static (`DISABLE_MODE_MAKE_STATIC`)
    - [x] Active (`DISABLE_MODE_KEEP_ACTIVE`)

### Collision

- [x] Layer (`collision_layer`)
- [x] Mask (`collision_mask`)
- [x] Priority (`collision_priority`)

### Input

- [ ] 🚧 Ray Pickable (`input_ray_pickable`)
    - Technically implemented, but hardcoded to `true` until Godot 4.1
- [x] Capture on Drag (`input_capture_on_drag`)

### Transform

- [x] Position (`position`)
- [x] Rotation (`rotation`)
- [x] Scale (`scale`)

## Methods

- [x] `get_overlapping_areas`
- [x] `get_overlapping_bodies`
- [x] `has_overlapping_areas`
- [x] `has_overlapping_bodies`
- [x] `overlaps_area`
- [x] `overlaps_body`

## Methods (`CollisionObject3D`)

- [x] `_input_event`
- [x] `_mouse_enter`
- [x] `_mouse_exit`
- [x] `create_shape_owner`
- [x] `get_collision_layer_value`
- [x] `get_collision_mask_value`
- [x] `get_rid`
- [x] `get_shape_owners`
- [x] `is_shape_owner_disabled`
- [x] `remove_shape_owner`
- [x] `set_collision_layer_value`
- [x] `set_collision_mask_value`
- [x] `shape_find_owner`
- [x] `shape_owner_add_shape`
- [x] `shape_owner_clear_shapes`
- [x] `shape_owner_get_owner`
- [x] `shape_owner_get_shape`
- [x] `shape_owner_get_shape_count`
- [x] `shape_owner_get_shape_index`
- [x] `shape_owner_get_transform`
- [x] `shape_owner_remove_shape`
- [x] `shape_owner_set_disabled`
- [x] `shape_owner_set_transform`

## Signals

- [x] `area_entered`
- [x] `area_exited`
- [x] `area_shape_entered`
- [x] `area_shape_exited`
- [x] `body_entered`
- [x] `body_exited`
- [x] `body_shape_entered`
- [x] `body_shape_exited`

## Signals (`CollisionObject3D`)

- [x] `input_event`
- [x] `mouse_entered`
- [x] `mouse_exited`

**Comment by mihe** [comment]
This tracking issue has served its purpose and will now be closed. 🫡

Any remaining work has had new issues created for it.
